### ISSUE TITLE
PointerEvents should have fractional coordinates

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/pointerevents#107]
PointerEvent spec doesn't override the [MouseEvent spec definition](https://www.w3.org/TR/DOM-Level-3-Events/#interface-MouseEvent) of <code>(clientX, clientY)</code> and <code>(screenX, screenY)</code> coordinates: all of them are integers. In Edge, PointerEvents (and not MouseEvents) have fractional client coordinates even though screen coordinates are always integers.

Chrome follows the spec but [wants to follow Edge](https://crbug.com/607948).
1. Should we spec this?
2. If yes, does it make sense to have both screen and client coordinates fractional, instead of only client coordinate as in Edge?

**Comment by scottgonzalez** [comment]
+1 for all fractional values

**Comment by patrickhlauke** [comment]
i'd be for changing those to `float`, unless there's some compat risk? @teddink ?

**Comment by teddink** [comment]
I agree with changing them to float for consistency reasons. I am not overly concerned about compat risks since we have had fractional values for those devices that support it for `deviceX/Y` for quite some time.

On the other hand, we are fairly sure that the underlying system does not provide fractional values for `screenX/Y`.

What's happening is that `screenX` directly takes the value passed to us from the system, specifically the `ptPixelLocation` in the [POINTER_INFO](https://msdn.microsoft.com/en-us/library/windows/desktop/hh454907%28v=vs.85%29.aspx).

For `clientX/Y` we do `ScreenToClient()` conversion of the `screen`, then convert to layout coordinates, then convert back to document coordinates. It seems like this process allows subpixel transforms.

**Comment by staktrace** [comment]
I'm in favor of making everything (including screenX/Y) float where feasible, for the simple reason that it's easy to always provide int values even if the type is spec'd as float, but not so the other way around. Also for example on some Firefox OS devices we had hardware actually reporting subpixel-valued touch events, and if we ever want to expose that level of precision to content then it makes sense to have floats instead of ints.

**Comment by RByers** [comment]
Discussed in the hackathon that Edge's behavior with `screenX/Y` is a bug - it's using physical pixels instead of CSS px units.  Andrew (Edge) has a bug to fix this, then it will be fractional too.

**Comment by RByers** [comment]
Note that [CSS OM View already updates MouseEvent](https://drafts.csswg.org/cssom-view/#extensions-to-the-mouseevent-interface) to define the co-ordinates as fractional.  Once implementations have aligned on this, I'm sure we can get it moved into the UI Events spec.  If, for web compat, we have to say that `mouse*` events always truncate, that's fine - then our spec can clarify that `pointer*` events have no such restriction.

Let's leave this issue open to remind ourselves to get the right spec updates for this.  I'm guessing it's probably not practical to write web-platform-tests for this (until we have w3c/uievents#120), right?

/cc @zcorpan @garykac

**Comment by RByers** [comment]
In our call today I said I'd file a bug on UI Events to adopt the `double` values.  There's already a bug at https://github.com/w3c/pointerevents/issues/602, but I don't think we can quite claim that implementations match this yet.

In Chrome, `(new MouseEvent('mousedown',{clientX:5.5})).clientX` still returns 5 (though @mustaqahmed is [fixing this](https://bugs.chromium.org/p/chromium/issues/detail?id=456625).

In Edge, even `(new PointerEvent('pointerdown',{clientX:5.5})).clientX`returns 5 (but 5.5 as expected in Chrome).  What's up with that @teddink, surely that's just a bug (given that the browser itself does generate events with non-integer co-ordinates) right?

So let's wait until we've got at least these implementation issues addressed and behaving consistently between Edge and Chrome before we push to adopt the IDL change into the UI Events spec.

WebKit and Gecko still use `long`, not `double` in their MouseEvent IDL.

**Comment by mustaqahmed** [comment]
Looks like we can partially test fractional coordinates even without w3c/uievents#120 , through trivial changes in the web-platform-test [pointerevent_constructor.html](https://github.com/w3c/web-platform-tests/blob/master/pointerevents/pointerevent_constructor.html).

@RByers: Do you think it's a reasonable thing to do even without a change in spec wording?   I am assuming that PointerEvents can be inferred to be based on the MouseEvent overrides in CSS OM View spec.

**Comment by RByers** [comment]
Yes, I think we should just test this here.

Ideally the the CSS OM View spec would have tests for fractional values passed to MouseEvent constructors (maybe it does already @zcorpan?). But regardless I thin it's fine to just update `pointerevent_constructor.html` for this.  It's already depending on the UI Events spec eg. for the test for `clientX`, no reason it can't depend on CSS OM View also. I'd just add a comment with the relevant spec link.

We should probably also be pushing for the OM View MouseEvent changes to be merged back into the UI Events spec now that there are at least 2 shipping implementations /cc @garykac.

**Comment by RByers** [comment]
Note that testing that fractional co-ordinates get passed through the constructor isn't quite the same thing as testing real browser-generated events.  So ideally we'd also use our automation hooks to test that too.  But rather than create but-yet more -manual tests, I think it's fine to just block that on w3c/uievents#120 (which is hopefully happening soonish - at least for Chrome).

**Comment by patrickhlauke** [comment]
@RByers (or anybody else) ... anything more on this than can/needs to be done?

**Comment by RByers** [comment]
I believe it should now be possible to test this, but I'm not entirely up-to-date on the status.  Maybe @NavidZ can take a look?

**Comment by NavidZ** [comment]
The current automation API only allows an element as the target and not the exact coordinates.
But I believe I should be able to make an element that the target coordinate lands on a fractional coordinate. I'll look into this.

**Comment by NavidZ** [comment]
We already have a [manual test](https://github.com/w3c/web-platform-tests/blob/master/pointerevents/pointerevent_fractional_coordinates-manual.html) for this usecase. I was going to use our click api but I realized it also expect the touch and pen inputs. I suggest waiting for this [PR](https://github.com/w3c/web-platform-tests/pull/10312/) to land to have synthetic pointer action API and then directly use that instead for the automation. I'll keep an eye on the progress on that front and will take care of updating pointerevent tests accordingly.
