### ISSUE TITLE
What is the relationship between setPointerCapture, PointerLock, and browser default behaviors?

### ISSUE THREAD

**Issue by mingchou** [w3c/pointerevents#135]
[Here](http://jsbin.com/masuya/2/edit?html,output) is the first test. It setPointerCapture to another element when mousedown on a input element with type=range. setPointerCapture works on Chrome Canary and the slider doesn't move. But the behavior is strange after pointerup and releasePointerCapture. Edge handles it as setPointerCapture doesn't be called.

[This](http://jsbin.com/giqopi/edit?html,output) is the second test of setPointerCapture with dnd. setPointerCapture works until dragstart. The difference between Edge and Canady is that Edge fires lostpointercapture after dragstart while Canary fire lostpointercapture when releasing mouse button.

[This](http://jsbin.com/huyocu/edit?html,output) is the third test. When you selected the text and drag it, setPointerCapture will not capture pointers after dragstart.

[This](http://jsbin.com/zasesu/edit?html,output) is the fourth test. One element setPointerCapture and the other requestPointerLock. Please ignore this case if it will be covered by [issue#131](https://github.com/w3c/pointerevents/issues/567). On Canary, requestPointerLock works but setPointerCapture not. On Edge, the result is opposite.

My question is will we define the relationships between browser default behaviors, dnd, pointerlock, and  setPointerCapture?

**Comment by RByers** [comment]
This is a great set of tests, thank you!
@mustaqahmed / @NavidZ can you take a look at our behavior vs. Edge for each of these and make a proposal for which you think is right?

Ideally I think we should try to say something about them (and have WPT tests for them) here in the PE spec for now, although ultimately the right long-term may be to make some updates to the HTML and PointerLock specs.

**Comment by RByers** [comment]
Discussed in the call today that we need to at least understand the differences in behavior today around these questions.  Then we can decide what changes specifically are required for V2.

**Comment by mustaqahmed** [comment]
To make the discussion more focused, I suggest splitting this issue.

I will create a new issue now to cover the PointerLock-vs-setPointerCapture problem (the fourth test in @mingchou's post) about which @NavidZ  and I had a quick discussion few hours ago.

**Comment by NavidZ** [comment]
Regarding the slider (1st paragraph) we match the behavior of Edge and use the pointer capture for the slider thumb pointer capturing. This way this is as if the thump is calling pointer capture in its pointerdown handler. Here is the [chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=701058) and it should be fixed in Canary.

Regarding the DnD issues (2nd and 3rd) I believe what Edge does again makes sense. So I filed [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=706106) to fix the behavior in Chrome.

As @mustaqahmed mentioned we discussed the suggested solution in w3c/pointerevents#176. 

I'm going to close this issue as I believe there is nothing more to discuss on this issue. @mingchou let me know if the solutions above and also the one suggested in w3c/pointerevents#176 makes sense and whether you agree with them or not.

**Comment by mingchou** [comment]
So UA calls setPointerCapture to capture the pointer to drag the slider when pointerdown on the input element with range type. Calling preventDefault and setPointerCapture to another node can stop dragging the slider and pointer events can be received by the captured node. Is my understanding correct?

I have no questions about the cases of DnD and pointerlock. Thanks for clarifying these.

**Comment by NavidZ** [comment]
Yup. That is what I saw in Edge and what we did in Chrome.
