### ISSUE TITLE
How should PointerLock vs setPointerCapture work together?

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/pointerevents#176]
This issue covers the PointerLock part of #135. Here is the original comment in that bug (by @mingchou):

> One element setPointerCapture and the other requestPointerLock. Please ignore this case if it will be covered by issue#131. On Canary, requestPointerLock works but setPointerCapture not. On Edge, the result is opposite.

In Chrome, pointer-capture comes after pointer-lock in the event flow just because we chose not to worry about both together in our initial implementation. We need to fix it for sure.

As for Edge, @NavidZ observed that it doesn't allow a requestPointerLock() after a setPointerCapture() but a setPointerCapture() after a requestPointerLock() doesn't work reasonably: PointerLock overrides the effect of capturing while the capturing target still gets got/lostpointercapture events.

What Edge does in the first case is the most reasonable solution to me: don't allow both of these together. The PointerLock spec [seems to suggest](https://w3c.github.io/pointerlock/#why-not-merge-with-mouse-capture-setcapture) these two can be active together (for the similar but non-standard setCapture() API instead), but I don't think the text there gives a definitive answer.

**Comment by NavidZ** [comment]
I was playing with different scenarios and interactions of these APIs. Particularly the fact that `requestPointerLock` is an async API and it is not in effect until user accepts that.
I found that defining the interaction based on which call was first seems more confusing.

Note that `requestPointerLock` is a more specific API (as it is only for mouse). I would say something that is more specific should generally take precedence over something that is more generic.

So how about pointer lock state always takes priority over the capture. So calling `requestPointerLock` doesn't do anything. But as soon as pointerlock is in effect if there is any capture going on (including the element that will get the pointerlock) the element should receive the `lostpointercapture`. Essentially, `lostpointercapture` should be fired before `pointerlockchange` if needed. While pointer lock is in effect `setPointerCapture` API should always fail. Since we don't have any generic exception, I wonder just silently not doing anything is fine or not similar to step 3 in "Setting Pointer Capture" section. WDYT?

**Comment by mustaqahmed** [comment]
Yes, the model "<code>requestPointerLock</code> dominates over pointer-capture" is simple and intuitive IMO.

- When PointerLock becomes effective while the mouse is captured, the capture would be implicitly released. So PointerEvent spec needs one more condition in the [Implicit Release section](https://w3c.github.io/pointerevents/#implicit-release-of-pointer-capture), which could be made generic (like "... when user agent decides to end capturing...") if we prefer not to call out PointerLock.

- When PointerLock is effective and a mouse capture request is made, an <code>InvalidStateError</code> looks more reasonable to me than silently dropping the call. Otherwise each <code>setPointerCapture</code> call would have to followed by a <code>hasPointerCapture</code> call which looks ugly. Alternatively, <code>setPointerCapture</code> can return a boolean status.

**Comment by NavidZ** [comment]
Reopening the issue until the test is also added.

**Comment by NavidZ** [comment]
The tests have been landed ([[1](https://github.com/w3c/web-platform-tests/blob/master/pointerevents/pointerlock/pointerevent_pointerlock_after_pointercapture-manual.html)] and [[2](https://github.com/w3c/web-platform-tests/blob/master/pointerevents/pointerlock/pointerevent_pointerlock_supercedes_capture-manual.html
)]).

**Comment by smaug----** [comment]
What does "If this method is invoked while the page has a locked element ([PointerLock]), throw an exception with the name InvalidStateError." mean? What is a "page"?
Does it contain top level document and documents in iframes or what? The spec doesn't explain this.
