### ISSUE TITLE
Should the spec defines how to handle when the pen's left button and the pen tip both are pressed?

### ISSUE THREAD

**Issue by LanWei22** [w3c/pointerevents#207]
One of the Wacom pens has two buttons on the side, the above one is configured as left button, which is the same as when we press the tip on the tablet. We should define how we handle the case when the tip is pressed the tablet and the button is also pressed. Should we ignore the button when the tip is pressed the tablet? Also, when we press the tip and we press other buttons, should we consider it as multiple buttons click at the same time or only care about the last pressed button?

**Comment by dfleck** [comment]
Here's some background on how the side switches work:
The buttons are configurable by the user. By default the tip is left click, and the side switches are right click and left double click.
There are two situations regarding cording (pressing more than one) settable by the user:
1) "TabletPC" bahaviour (click and tap). In this case the side switches don't activate until the tip is clicked (so side switches are always combined with the tip). So to do a right click, you press the side switch then click with the tip and a right click is sent - not a left. This can make targetting easier since the action occurs on tip down (a downward motion) instead of pressing the side switch (a sideways motion) but it does require two actions and precludes cording.
2) True cording. An example here is setting a side switch to do a keyboard modifier, such as option. In this case the tip does a left click, but a side switch plus tip does an option click. This is useful in Photoshop where the option key inverts the action (draw becomes erase, dodge becomes burn)

Since a lot of the events thrown by the driver at a low level, the buttons will act as defined in the settings before PE can do anything (if a button is set to right click, a right click event will be sent by the driver).

My opinion:
If the user sets the side switch to "barrel button", the side switch and tip switch should be treated independently and the state of both buttons should be reported. Otherwise the driver will perfomr the actions specified by the settings.

**Comment by scottgonzalez** [comment]
I agree with @dfleck. For the scenario reported by @SummerLW, I would not expect anything to happen when the "left" button is pressed while the tip is already in contact. If two buttons represent the same thing, they should share an active state. In terms of events, you cannot press down on a button that is already down, even if there are multiple physical buttons to press.

**Comment by patrickhlauke** [comment]
In short, I believe this doesn't need further spec work, as it's something handled by the OS/device (i.e. that if both pen contact AND button for left click are pressed, it counts as the same thing / there's no way to differentiate)
