### ISSUE TITLE
Touch/Trackpad finger position

### ISSUE THREAD

**Issue by felipenmoura** [w3c/pointerevents#228]
Hi.
I hope this is the right place to mention this. If it is not, could you please point in the right direction?

What would it require for us to have an API to get the exact position of fingers/touches from the trackpad? I mean, touches even if not pressed, the equivalent to "mousemove" in the trackpad.

For example, let's say someone wants to write a WebApp in which you could sign something, or simply use a (good) handwriting feature instead of pressing/clicking.

Example:
Let's say I draw an "A" in the left side of my trackpad, then I draw a "B" in the right side of the trackpad. On the screen, they will overlap, with both letters in the same place.
That's why I'm talking about the touch position in the trackpad.

This is a feature that is supported for native apps...I wonder why shouldn't it be for the web :)
As I can see, the OS passes this info down to native applications (I saw some Java and Objective C doing that), so, browsers could be able to use this info and provide an API for that.

Thanks.

**Comment by mustaqahmed** [comment]
So you are thinking something like `(rawX,rawY)`?  Do we have trackpads with hardware+driver support for it?

Moreover, we would need OS support to tie the mouse cursor position with the trackpad finger position because it would be a terrible UI if the drawing is off from visible mouse cursor position (`(rawX,rawY)` vs `(x,y)`).  Then there is the question of input/output precision because if the trackpad rectangle maps to a big screen, every pixel in the screen should be reachable through a finger position.

Perhaps the native apps you mentioned have the answers.  Please provide some details.

**Comment by felipenmoura** [comment]
Very important point.
I will try and find out more on those native APIs, but as far as I can tell, we would need:

- **Track proportion:** How squared or rectangular is the trackpad
- **List of touches:** once it is not a click or mousedown, but the equivalent of a "mousemove"

Each touch would have:

- **x:** A spacial reference for x, in percentage
- **y:** A spacial reference for y, in percentage
- **pressed:** A boolean saying if that touch is currently pressed or not

Also interesting to have, but I'm not sure OSs offer support for this, would be:

- **precision:** How wide is the touch...let's say the user is passing their whole thumb...or using a touch pen

If we always get the % information for the position of a touch, and we have the trackpad proportion, we can infer the touch position on the screen.

This will not only allow developers to create things that nowadays still require native app, as it will help our tools to emulate touch screen and gestures while developing.

**Comment by felipenmoura** [comment]
So, does this make sense? :)

**Comment by mustaqahmed** [comment]
My opinion is that scaling trackpad rectangle onto screen rectangle (so that there's a 1:1 mapping between a trackpad position and a screen position) won't be useful because before actually making a tap, a user won't know where on screen the tap is going to land (since trackpad is an indirect manipulation device unlike a touchscreen).

It seems Edge is shipping something close, where (among other things) trackpad position is still relative to mouse pointer position.  See #206 and [blog post for the Edge feature](https://blogs.windows.com/msedgedev/2017/12/07/better-precision-touchpad-experience-ptp-pointer-events/).

**Comment by felipenmoura** [comment]
I understand, but that is actually the point.

For example, on macbook's "preview" app, you can save your hand written signature.
The way you can sign is totally intuitive! You simply sign it in your trackpad. It doesn't matter where the pointer is. You have the area for you to write and that's all (you don't need to press the trackpad area, just touch it and move the finger, and you can even jump or skip areas like spaces between letters or lines). That is an experience that is just impossible for us to offer our users, using web technologies. I can think of interesting use-cases for games too.
Also, developer tools could use this to emulate gestures and touches.

Maybe we wouldn't need to scale the trackpad to the screen. Instead, we might have an API in which the user(developer) specifies the size of the rectangle they want to represent the trackpad.

And in all of this we are talking about a "passive" trackpads. There are trackpads with feedback (like a small bump of vibration) that we could think of, in the future implementations of this API.

**Comment by patrickhlauke** [comment]
Closing this for now as a possible future enhancement, but out of scope for v2.

**Comment by abemilk** [comment]
Any updates to this?

**Comment by patrickhlauke** [comment]
discussed this at today's pointer events working group meeting https://www.w3.org/2023/02/01-pointerevents-minutes.html#t04

while we understand the developer need/use cases here, we feel it's not quite the appropriate fit for the pointer events API - it is arguably far more low-level, and may be more closely related to the pointer lock API or a more generalised sensors API.

we recommend posting a proposal (including use cases) to the Web Incubator Community Group (WICG) https://discourse.wicg.io/ where it may find more traction and a more appropriate venue.
