### ISSUE TITLE
Explicit mention that `pan-x pan-y` is equivalent to `auto`?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#23]
Currently, it's implict in the spec language that `touch-action: pan-x pan-y` essentially is equivalent to `touch-action: auto` with regards to default scroll handling. However, as I just had to delve into https://github.com/hammerjs/hammer.js/pull/855 and fix what seems to be a misunderstanding of those values, I'm wondering if we want an explicit informative note/boxout that says that. Happy to do a PR, but wanted to get thoughts here first?

**Comment by mbrubeck** [comment]
I'm hesitant to say that these two values are "equivalent" since `touch-action: auto` may (and in practice does) allow more default actions than `touch-action: pan-x pan-y`.  Even with the "with regards to scroll handling" qualifier, it seems like this might confuse things more than clarify them.

However, maybe we can expand the definition of `auto` to explicitly say that it allows panning in both directions, as well as zooming and possibly other actions?

The author of the hammer.js code seems to have reversed the meanings of _all_ `touch-action` values. The confusion doesn't seem specifically related to `auto` or `pan-x pan-y`.  For example, a simple `touch-action: pan-x` was reversed in meaning.  I don't think adding text specifically about `auto` being equivalent to `pan-x pan-y` would help prevent that.

Perhaps instead we should add some more code samples, and clarify the existing ones.

**Comment by patrickhlauke** [comment]
> Perhaps instead we should add some more code samples, and clarify the existing ones.

I'd buy that for a dollar. Let me concoct something (as I was going to anyway for my http://patrickhlauke.github.io/getting-touchy-presentation/ presentation)

**Comment by RByers** [comment]
Right, we were careful to avoid ANY "equivalent" legal touch-action values.  If there's confusion that  `pan-x pan-y` means "scrollable anywhere, but no zooming" we could consider adding a simple `pan` value (similar to how `pan-x` replaces `pan-left pan-right`).  But we of course then couldn't make `pan-x pan-y` illegal (without breaking existing sites).

**Comment by patrickhlauke** [comment]
having sat on this for a while, i think we're actually good as we are now...so just going to close this :)
