### ISSUE TITLE
ReSpec complains about normative references in informative sections

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/pointerevents#271]
@plehegar @NavidZ @mbrubeck while we're looking at the normative/informative mixup, it's also worth noting that ReSpec warns of 3 normative references inside informative sections

```
Normative references in informative sections are not allowed. Remove '!' from the start of the reference [[!UIEVENTS]]. See developer console to find offending element.
Normative references in informative sections are not allowed. Remove '!' from the start of the reference [[!HTML5]]. See developer console to find offending element.
Normative references in informative sections are not allowed. Remove '!' from the start of the reference [[!COMPAT]]. See developer console to find offending element.
```

I'll admit that I'm no expert on the matter of when a reference needs to be normative vs informative ... could somebody with a clearer idea of this take a look? (in fact, our current editor's draft has 4 such warnings, but the change in https://github.com/w3c/pointerevents/pull/270 takes care of one of them)

**Comment by andreastt** [comment]
The issue is that the [Introduction](https://w3c.github.io/pointerevents/#intro) is marked as informative through `<section id=intro class=informative>`, and as the error indicates, informative sections cannot have normative references because they per definition are not implementation requirements.

Assuming HTML, UI Events, and Compat are referenced in another normative section, you can just change the three references in informative sections from `[[!UIEVENTS]]` to `[[UIEVENTS]]` by removing the exclaimation mark.

**Comment by patrickhlauke** [comment]
thanks @andreastt - i was aware of the technical "why", but your explanation made it clearer for me as to the "if I change this in code, what does it actually *mean* from a spec standpoint". I've made the change here https://github.com/w3c/pointerevents/commit/d2779fe71e3b1c26d6b4657ad0330bed378b8b69 (only substantive change is that `[COMPAT]` is now only an informative, rather than normative, reference - which seems correct to me)
