### ISSUE TITLE
It is unclear how predicted events' timestamps should relate to actual dispatched events

### ISSUE THREAD

**Issue by smaug----** [w3c/pointerevents#282]
Is it possible that there will be actual events dispatched sooner than what predicted events' timestamps hint?
Perhaps some small clarification in the spec would be enough.

**Comment by patrickhlauke** [comment]
after https://github.com/w3c/pointerevents/pull/364 is hopefully merged, mind fleshing this out some more? (or has the reordering/grouping of the explanations in #364 obvioated the need for this?)

**Comment by patrickhlauke** [comment]
to me, though, it seems that predicted events are only valid/good/to be considered for the current `pointermove`/`pointerrawmove` that you're querying on. as soon as a more recent "proper" `pointermove`/`pointerrawmove` comes in, those predictions are to be considered obsolete.

predicted events will always have future timestamps compared to their "parent" event where they came from. whatever timestamp any real following events have compared to those predicted events is likely not useful to know, since you'd not consider them anymore as soon as a proper event comes in.

**Comment by patrickhlauke** [comment]
@smaug---- would a simple note (in the new predicted events list section) along these lines suffice?

```
Note that predicted events are only "valid" (or some word to that effect) until the next pointer event is dispatched. It is possible, depending on how far into the future the user agent predicts events, that regular pointer events are dispatched earlier than the timestamp of one or more of the predicted events.
```

**Comment by smaug----** [comment]
That sounds reasonable.
