### ISSUE TITLE
Update the WebKit status in README.md

### ISSUE THREAD

**Issue by graouts** [w3c/pointerevents#288]
Since Pointer Events are enabled by default in both Safari on iOS 13 and Safari 13.0 for MacOS Catalina and Mojave, I think the README.md should be updated to say that WebKit support is In Development, at least until those software releases ship to the wide public.

**Comment by dtapuska** [comment]
A number of WPT tests are still failing.
https://wpt.fyi/results/pointerevents?label=master&label=experimental

What is the status of WebKit fixing them?

**Comment by graouts** [comment]
For the tests that are expected to work on macOS (*_mouse.html), this status is quite old already since this STP release is a few releases behind. The pass rate is higher on a number of tests and I'm working on fixing a few remaining tests that are not passing 100%.

For the touch tests (*_touch.html), there is no relevant data on this page since these tests could not work on macOS, only on iOS. The touch-specific tests have 100% pass rate on iOS 13 betas at the moment.

**Comment by NavidZ** [comment]
I agree that the readme can be updated nevertheless. Definitely the "opposition" is not valid anymore. I suggest sending a PL and adding any links you see fit to the text similar to the other browsers.

**Comment by dtapuska** [comment]
I thought that webkit didn't support any of the touch-action directives other than auto & manipulation, and that was where the opposition is. You need to do the manual tests to see that it passes them.

Perhaps iOS is only passing 100% of automated tests?

**Comment by patrickhlauke** [comment]
it should support `touch-action: none` as well (not tested directly, but it's mentioned and used in the relevant demos on https://developer.apple.com/videos/play/wwdc2019/203/)

**Comment by graouts** [comment]
We support every feature defined in the [Pointer Events specification](https://w3c.github.io/pointerevents), including the various `touch-action` values. We have also added further automated testing using testharness.js that we plan to submit once the dust settles.

At any rate, I think no matter what way one chooses to measure, our implementation should at least be considered "In Development". It's not a big deal whether the README is updated, I just saw that in passing and thought it could be updated.

**Comment by dtapuska** [comment]
Cool.. my mistake for some reason the github mirror of webkit on search wasn't showing the pan values. I checked trac and I see them there. That is great!

**Comment by NavidZ** [comment]
@graouts sounds good. I forgot whether you guys could send pull requests or just review them (legally speaking). But let me know and I can send the pull request instead if you prefer.

Kind of tangent to this topic but since you brought up the link to the [main spec V2](https://w3c.github.io/pointerevents/) I wonder whether you have any comments about features in the [extension doc](https://w3c.github.io/pointerevents/extension.html). We were planing to move towards a V3 with those new features and anything else that might come up. It also has a few new touch-actions values (mainly directional ones). I'll try to send each feature as a separate pull request to the main spec and cc folks from different vendors on each so they are aware of each change separately and we can discuss them on the pull request if there is any general objection.

**Comment by graouts** [comment]
I don't think I can file a pull request I'm afraid @NavidZ. If you don't mind, thanks for making one.

I have seen the extension document but have not researched it very much, not sure of where it stood in the context of the Pointer Events standardization process. When pull requests come up in this repository, I will take a look and comment.
