### ISSUE TITLE
Reserved pointerIds for special cases

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/pointerevents#343]
A recent [change](https://github.com/w3c/pointerevents/pull/317/) in the spec to support "click as a PointerEvent" assumed that a zero `pointerId` is reserved for non-pointing devices.  This is not backward compatible because we had no normative text in the spec about it.

A bit of history: several years ago we had added [this note](https://w3c.github.io/pointerevents/#dom-pointerevent-pointerid) around this behavior, perhaps after Chrome copied (EdgeHTML-based) Edge's behavior around `pointerId`s.  But we didn't formalized the behavior.

If I recall correctly, another behavior Chrome copied from Edge was reserving `pointerId ==1` for mouse.  This seems useful because mouse events are always tied to a single pointing device (which is unlike touch---each finger gets a new `pointerId` on every `pointerdown`).  This was not spec-ed either. 

I discovered today (following this [comment](https://github.com/w3c/pointerevents/pull/317/#discussion_r544434382)) that Firefox uses `pointerId ==0` for mouse, which breaks both assumptions above, while being spec compliant!

@smaug---- @NavidZ: Can we standardize some reserved `pointerId` values to fix this?

**Comment by mustaqahmed** [comment]
I missed that @smaug---- has filed #342 for the same problem few minutes ago!

**Comment by liviutinta** [comment]
I tested Safari Version 14.0 (15610.1.28.1.9, 15610) on macOS 10.15.7 and it uses `pointerId == 1` for mouse.

**Comment by patrickhlauke** [comment]
> This seems useful because mouse events are always tied to a single pointing device

in theory, i thought we wanted to allow multiple mice to be used at the same time (or at least, not limit it) - though currently I think only something like X Window Manager actually allows this in practice (from what I heard, never tried it).

Instead of special-casing `pointerId == 1` for mouse (as I don't think it'd be good practice to encourage authors to start relying on *that* ... they should be checking `pointerType` and, if necessary, keeping track of whatever `pointerId` that event has), would it be possible to change the behaviour in Gecko to not use `0`, and to keep *that* value reserved for cases where the event came from a non-pointer device?

**Comment by patrickhlauke** [comment]
I would hope that changing Gecko's behaviour now (if that's possible of course ... I'm making assumptions here @smaug---- ) would have low risk, since I doubt (citation needed) many authors are using PE at this stage still, and of those that do, I would seriously hope none are doing an id check (since they'd currently already have to do some "either 0 if Firefox, or 1 if Chromium/Safari/legacy Edge)" logic which would strike me as making little sense)

**Comment by smaug----** [comment]
That might be possible. Other option could be to return -1 for non-pointer types. The attribute has type 'attribute long' after all.

**Comment by patrickhlauke** [comment]
Ah, good point. that may be even cleaner, conceptually?

**Comment by smaug----** [comment]
Yeah, I think it would be easier to understand. Negative values after all have been used often for "error" or "non-valid" cases in traditional APIs.

**Comment by mustaqahmed** [comment]
> in theory, i thought we wanted to allow multiple mice to be used at the same time (or at least, not limit it) - though currently I think only something like X Window Manager actually allows this in practice (from what I heard, never tried it).

@patrickhlauke: We investigated the multi-mouse scenario when we implemented (in Chrome) compat mouse event support for multiple active pointers (there can be at most 3 active pointers simultaneously, one per `pointerType`).  Every OS we tried shows a _single_ mouse pointer on screen if multiple mice are attached.  IIRC Windows is the only OS that actually "remembers" every mouse position even though it still shows only the pointer that has moved last.  Based on these observations, we concluded that compat mouse events (in particular `mouseover`/`out`/`enter`/`leave` events) for the multiple active pointers case should be wired based on a "single pointer on screen" idea.  Let's not revisit this assumption unless it becomes necessary :)

> I don't think it'd be good practice to encourage authors to start relying on that ... they should be checking pointerType and, if necessary, keeping track of whatever pointerId that event has...

This makes perfect sense but I still worry about backward compatibility because Edge shipped mouse id == 1 many years before [Chromium did](https://codereview.chromium.org/1426643008).  I remember having discussions with @NavidZ when we [decided to reserve](https://bugs.chromium.org/p/chromium/issues/detail?id=546658#c3) a mouse-specific id, but I can't remember if we saw a specific breakage.

> Yeah, I think it would be easier to understand. Negative values after all have been used often for "error" or "non-valid" cases in traditional APIs.

@smaug----: I agree with this interpretation.  But since a click event from keyboard interaction is neither an error nor an invalid event, isn't it better if we avoid a negative `pointerId` for this case?

**Comment by smaug----** [comment]
But obviously keyboard isn't a pointer, so having a pointerId is rather weird case. Why is 0 any better than -1?

**Comment by smaug----** [comment]
but yes, -1 isn't from spec point of view more backwards compatible than 0. But it is from implementation point of view.

**Comment by smaug----** [comment]
The more I think, the more I feel -1 would be better for the cases when the event isn't for any pointer.

**Comment by smaug----** [comment]
@mustaqahmed can you see any reason why to not make that change in the specs?

**Comment by mustaqahmed** [comment]
Thanks @smaug---- for explaining your points.  Let's go ahead with `pointerId = -1`.

**Comment by patrickhlauke** [comment]
Are we happy to leave the "reserve a specific value for mouse" aspect aside though? I'd be happier this way from a purity point of view, since we do want to allow - in theory at least - multiple pointers of the same type (otherwise we would need to likely also say something like mouse is always primary etc). If implementations in OS or browsers want to reserve a particular id, that should be up to them (to then also deal with the fallout if it turns out reality doesn't match the expectation of there only ever being just one mouse, if a new device or OS or whatever comes out that handles multi-mouse scenarios differently).

And as said, I really don't want to encourage authors (by having it explicitly in the spec) to just start making assumptions on pointer type etc based purely on a reserved `pointerId` (again mostly from a purity point of view).

**Comment by mustaqahmed** [comment]
Not reserving a specific value for mouse sounds good.  If Firefox ever discovers compat problems with `0` for mouse, we can always reopen this issue in future.
