### ISSUE TITLE
event.movementX is always zero in pointerup event.

### ISSUE THREAD

**Issue by trusktr** [w3c/pointerevents#344]
No matter how fast I move my mouse, `event.movementX` (I haven't checked `movementY`) is always `0`. I get expected values in `pointermove` events, just not in `pointerup`. 

Is this expected?

**Comment by patrickhlauke** [comment]
As the PointerEvents spec itself doesn't deal with any of these properties, this sounds to me like either something that should be filed against a particular browser engine (or does it happen consistently in all engines?), or against the PointerLock spec that defines those properties https://w3c.github.io/pointerlock/ (but happy to open this issue again if it turns out I'm wrong)

Also, I've not looked at the PointerLock spec in a while, but just thinking this through: wouldn't there theoretically be no movement just for down or up events? There'd be a movement just at the last move event, before the actual up or down get fired?

**Comment by trusktr** [comment]
Ah, interesting. I didn't look to see which spec the properties came, but I certainly would expect them to behave a certain way with pointer events. Namely in my case, I definitely expect movementX to have a value other than zero.

In order to work around the issue that I see (in Chrome at the moment), I need to ignore the `movementX` property, and instead I track deltas my self using only `clientX` and it gets a bit complicated.

Instead of this:

```js
let isDragging = false;

this.scene.addEventListener("pointerdown", (event) => {
	isDragging = true;
});

this.scene.addEventListener("pointermove", (event) => {
	if (!isDragging) return;

	const delta = event.movementX;
	// use delta
});

this.scene.addEventListener("pointerup", (event) => {
	if (!isDragging) return;
	isDragging = false;

	const delta = event.movementX;

	if (delta !== 0) {
		// use delta, etc, to fling the object
	}
});
```

We have to do this: 

```js
// Keeps the last two pointermove clientX values
let xStack = [0, 0];

function addX(x) {
	xStack.shift();
	xStack.push(x);
}

let isDragging = false;

this.scene.addEventListener("pointerdown", (event) => {
	isDragging = true;
	addX(event.clientX);
});

this.scene.addEventListener("pointermove", (event) => {
	if (!isDragging) return;

	const lastX = xStack[1];
	const delta = event.clientX - lastX;
	addX(event.clientX);

	// ... use delta ...
});

this.scene.addEventListener("pointerup", (event) => {
	if (!isDragging) return;
	isDragging = false;

	// We want the second-to-last pointermove's clientX value here, because
	// the current pointerup has the same clientX as the last pointermove event.
	const secondToLastX = xStack[0];
	let delta = event.clientX - secondToLastX;

	if (delta !== 0) {
		// ... use delta ...
	}
});
```

**Comment by trusktr** [comment]
I tried in both Chrome/Chromium and Firefox, and get the same result.

Here's a live demo (fling the cube):

https://codepen.io/trusktr/pen/rNMrvOY

Note in the console that the output on `pointerup` is the same in both browsers: `event.movementX` is always zero.
