### ISSUE TITLE
Consider adding API to get predicted points

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#38]
Some platforms have built-in prediction algorithms which apps would ideally handle differently from confirmed points (eg. a painting app would use predicted points only temporarily).  We could have an API directly similar to #22 but in the opposite time direction (instead of the past points, it's the future ones).

**Comment by RByers** [comment]
See "reducing latency" [here](https://www.raywenderlich.com/121834/apple-pencil-tutorial) for a concrete example of where this really matters in another platform.

**Comment by tdresser** [comment]
This appears to be extremely important for painting applications.

[Here](https://drive.google.com/file/d/0B7mjRvOU-oG-UHE1c1NFYU41N3M/view?usp=sharing)'s a comparison of OneNote (which uses Windows' predicted points API) and Edge, which doesn't expose predicted points.

Sorry for the terrible resolution video.

Based on some rough frame counting, OneNote has an effective end-to-end latency of 2 frames, whereas Edge has an effective end-to-end latency of about 4 frames.

Much of this is due to OneNote using predicted points.

After each of the short strokes at the beginning of the video, you can see the error prediction introduces, as OneNote draws the stroke a bit too long, and then shortens it soon after. Edge doesn't have this error, but has much more latency when drawing long lines.
