### ISSUE TITLE
Add support for laptop touchpads responding to the `touch-action` prop

### ISSUE THREAD

**Issue by NashJames** [w3c/pointerevents#478]
Hi!

My current work involves building a service adjacent to Google Maps, with a large number of map pins rendered on top of the map layer. We've had massive unexpected issues with users on laptops hovering their mouse pointer on any map pin or component rendered over the map and then using the two-finger gesture to zoom in. Instead of zooming the map, this will zoom in the browser and they often have no idea how they managed it, or how to rectify the situation.

We tried `touch-action: none;` as a method of preventing it but discovered it only applies to actual touch screens. I raised an issue with the Firefox team [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1849690). They support the idea but didn't want to introduce something non-standard that other popular browsers also haven't yet implemented.

Thanks for taking the time to consider this! It will greatly improve our UX.

**Comment by patrickhlauke** [comment]
I've commented on the bugzilla issue https://bugzilla.mozilla.org/show_bug.cgi?id=1849690#c6 but for reference here:

> my question would be: is the gesture performed on the trackpad analysed/processed by the browser itself, or is it lower down (e.g. some driver/utility at OS level) and what is actually being sent to the browser are effectively scrollwheel / CTRL+scrollwheel events? if the latter, it would probably not make sense/should not be directly possible to prevent the behaviour using touch-action, and the OP should instead listen for, and preventDefault(), scrollwheel events?

> [...] touch-action would be inappropriate in this case, and that the more appropriate approach for the OP is to explore preventing scrollwheel events (otherwise, you would end up in a similarly strange situation where touch-action would otherwise prevent actual CTRL+scrollwheel actions done with a mouse rather than a trackpad/touchpad).

**Comment by patrickhlauke** [comment]
based on more info from one of the Firefox devs (I assume?)

> the OS sends a dedicated message (via the DirectManipulation interface in the case of Windows), we use (translate) the message for pinch in/out.

which then brings me to

> Ah, in which case, touch-action should be applicable then https://w3c.github.io/pointerevents/#declaring-direct-manipulation-behavior and indeed Firefox should honour it

I don't think there's any change / clarification required for either of these resolutions on the actual PE spec. this second scenario here is up to Firefox to implement, if they so wish.

**Comment by NashJames** [comment]
@patrickhlauke Following the discussion [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1849690), should this issue be re-opened? If I'm interpreting your last comment correctly, you agree with this step forward as an additional clarification of the current `touch-action` spec than any additional new props.

Hopefully a more encompassing definition should encourage browsers to support this and any related props for touchpads.

Thanks for your help on this and apologies for the delay (I've been away a short while).

**Comment by theres-waldo** [comment]
Just wanted to chime in as a Firefox engineer: if the intent of the spec is that `touch-action` **should** apply to touchpads, I don't think that's sufficiently clear in the current spec text (and indeed, none of the three major browser engines seem to have interpreted it that way so far).

The only place touchpads are mentioned in the spec is this note:

> In some cases, touchpads (like those found on a laptop) will allow the user to scroll by "dragging" on the touchpad. However, this is generally achieved by the touchpad generating "fake" mouse wheel events, so this wouldn't count as a direct manipulation.

Here's what touchpad scroll and zoom gestures currently produce:

 * At the UI toolkit level (what the browser implementation sees), they generally produce some sort of "touchpad scroll" or "touchpad zoom" events.
   * These are distinct from events produced by a click-wheel mouse, and have more granular deltas.
   * But they're also distinct from `touch` events, in that we don't have information about the individual touch points (and even if we did, those touch points would not have a direct correspondence to points on the page the way they would in case of a touchscreen).
 * At the web content level (what the page sees), they produce `wheel` events (with the Ctrl modifier set in the case of zoom gestures); one might describe these as "fake" in the sense that no actual mouse wheel was used (nor Ctrl key pressed).

Given the above, it's not clear to me whether such events should be considered "direct manipulation".

If that's the intention, I'd like to suggest:
 * Making this more explicit in the spec.
 * cc'ing relevant Blink and Webkit engineers on this issue to make sure they're on board with this direction, so that in implementing this in Firefox we can be confident we're not introducing compat issues

**Comment by patrickhlauke** [comment]
> Just wanted to chime in as a Firefox engineer: if the intent of the spec is that `touch-action` *should* apply to touchpads, I don't think that's sufficiently clear in the current spec text

the spec leaves the decision up to individual implementations whether or not they treat/consider touchpads direct manipulation devices (and hence subject to `touch-action` logic) or not.
