### ISSUE TITLE
What happens when the pointer capture target is removed from DOM?

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/pointerevents#487]
DOM changes potentially affects both the variables [`pending pointer capture target override`](https://w3c.github.io/pointerevents/#dfn-pending-pointer-capture-target-override) and 
[`pointer capture target override`](https://w3c.github.io/pointerevents/#dfn-pointer-capture-target-override).  The current spec doesn't say what happens to them after a DOM change.

1. Should we change an element reference to `null` when the element gets disconnected so that the (pending) capture becomes ineffective?
2. Should we keep the element reference as-is, so any event dispatch to it fails silently until the element is re-attached?
3. Should we follow the recent consensus in https://github.com/web-platform-tests/interop/issues/380 that the reference will be updated to the still-connected ancestors?

**Comment by flackr** [comment]
I think the most reasonable expectation is that we only clear the pending pointer capture target override and then in the next [Process pending pointer capture](https://w3c.github.io/pointerevents/#process-pending-pointer-capture) we will dispatch lostpointercapture.

**Comment by mustaqahmed** [comment]
To add a bit more context from PEWG discussion today, we agreed that the second para in [Implicit release of pointer capture](https://w3c.github.io/pointerevents/#implicit-release-of-pointer-capture) section covers the issue except for the timing for the `lostpointercapture` event dispatch.  The current text seems to suggest the dispatch is synchronous with DOM updates, bypassing the lazy dispatch in [Process pending pointer capture](https://w3c.github.io/pointerevents/#process-pending-pointer-capture).

We will update that second para to utilize the lazy dispatch.

**Comment by flackr** [comment]
BTW I think the state to track this may be slightly more complex. [Process pending pointer capture](https://w3c.github.io/pointerevents/#process-pending-pointer-capture) says:

> If the [pointer capture target override](https://w3c.github.io/pointerevents/#dfn-pointer-capture-target-override) for this pointer is set and is not equal to the [pending pointer capture target override](https://w3c.github.io/pointerevents/#dfn-pending-pointer-capture-target-override), then fire a pointer event named [lostpointercapture](https://w3c.github.io/pointerevents/#dfn-lostpointercapture) at the [pointer capture target override](https://w3c.github.io/pointerevents/#dfn-pointer-capture-target-override) node.

However, if the [pointer capture target override](https://w3c.github.io/pointerevents/#dfn-pointer-capture-target-override) lost capture because it was removed from the dom we should be dispatching lostpointercapture at the document. One way to do this without adding additional state is in https://w3c.github.io/pointerevents/#implicit-release-of-pointer-capture we could change the [pointer capture target override](https://w3c.github.io/pointerevents/#dfn-pointer-capture-target-override) to the document and the [pending pointer capture target override](https://w3c.github.io/pointerevents/#dfn-pending-pointer-capture-target-override) to null so that the "document" immediately loses pointer capture.

**Comment by mustaqahmed** [comment]
Yes, thanks, that's the exact lazy dispatch I meant.  This works nicely even when new capture/release requests are made between the node-deletion and the firing of `lostpointercapture` event.
