### ISSUE TITLE
Clarify `mousedown` event target if the preceding `pointerdown` event listener removes the target

### ISSUE THREAD

**Issue by masayuki-nakano** [w3c/pointerevents#492]
https://github.com/web-platform-tests/interop/issues/380#issuecomment-1787398235

Spinning out from the above issue.

Currently, only Chrome dispatches a `mousedown` event to parent element when a `pointerdown` event listener removed the event target.

**I** think that Chrome's behavior may lead odd behavior because user tried to click under the pointer, not its parent (or ancestor). However, the `mousedown` may cause running event listeners of them. This must be trouble if the element is not visually in the parent or ancestor element.

On the other hand, Safari dispatches a `mousedown` event on the removed child element, but I think that this is not required.

In my understanding, `mousedown` event should not be fired if the preceding `pointerdown` event removed the target. And I think this can be applied to other sets of a pointer event and a fallback mouse event.

I also found one odd thing of Chrome's behavior.
https://jsfiddle.net/d_toybox/m18jpnae/
```js
e.addEventListener("pointerdown", event => {
  event.target.remove();
});
addEventListener("click", () => alert("clicked"));
```
https://jsfiddle.net/d_toybox/m18jpnae/1/
```js
e.addEventListener("mousedown", event => {
  event.target.remove();
});
addEventListener("click", () => alert("clicked"));
```
In the first case, Chrome dispatches `mousedown` on the parent, and then, `mouseup` on the parent too. Therefore, `click` event should be fired from UI Events point of view. However, Chrome does not dispatch it. I guess Chrome fixes the candidate of the `click` event at dispatching `pointerdown` and the removal of the event target causes stopping dispatching it.

@mustaqahmed, @smaug----, @garykac

**Comment by mustaqahmed** [comment]
Thanks @masayuki-nakano for filing this issue.  Wondering what UI Event spec says (or implies) about dispatching vs skipping click event in this case.  Let's continue the discussion here.

(To me, Chrome not firing click seems like a bug, btw.)

---

I wanted to clarify one thing about the WPT that brought up this discussion: [pointerevent_after_target_removed.html](https://wpt.fyi/results/pointerevents/pointerevent_after_target_removed.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-events).

When the WPT was picked as an Interop 2023 goal last year, we didn't intend to cover interleaved pointer+mouse event dispatch.  Unfortunately, while addressing #377 and #380, we unintentionally added two sub-tests for the interleaved case instead of adding mouse-only sub-tests ([CL](https://chromium-review.googlesource.com/c/chromium/src/+/4854903/2/third_party/blink/web_tests/external/wpt/pointerevents/pointerevent_after_target_removed.html)).  We will correct the mistake now, and preserve the interleaved case as a tentative test for this issue.

**Comment by masayuki-nakano** [comment]
@mustaqahmed Thank you.

> we unintentionally added two sub-tests for the interleaved case instead of adding mouse-only sub-tests ([CL](https://chromium-review.googlesource.com/c/chromium/src/+/4854903/2/third_party/blink/web_tests/external/wpt/pointerevents/pointerevent_after_target_removed.html)). We will correct the mistake now, and preserve the interleaved case as a tentative test for this issue.

Thanks. And if somebody is still writing the patch, I'd like you guys to split the assertion to multiple ones like [this test](https://searchfox.org/mozilla-central/rev/fe8b30e982c86d26ccf1f14d825c0de870b91f27/testing/web-platform/tests/uievents/mouse/synthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative.html#120-173)? The assertions check too many things. Therefore, it takes long time to understand the result and the investigation result requires big tables when we comment the result in issues.

**Comment by masayuki-nakano** [comment]
It seems that it's cleared around:
* https://w3c.github.io/pointerevents/#the-pointerdown-event
* https://w3c.github.io/pointerevents/#mapping-for-devices-that-support-hover

**Comment by smaug----** [comment]
I think dispatching mousedown to the parent makes sense, since that way the page gets mousedown and mouseup, not only mouseup. And I'd expect to see click in that case, given that there was down+up.

But, if no browser fires click in that case, it might be a bit risky to change the implementations to fire click.

**Comment by mustaqahmed** [comment]
These [WPTs](https://wpt.fyi/results/pointerevents?label=experimental&label=master&aligned&q=interleaved.tentative.html) cover this case, including click event and moved DOM element.

**Comment by flackr** [comment]
Currently it looks like for the removed case no browser fires click, however if the element is moved ([test case](https://jsfiddle.net/flackr/grv2956n/5/)) it looks Firefox does and Chrome and Safari don't.

Also it's worth noting I've seen a bug reported around not firing click when reordering elements: https://bugs.chromium.org/p/chromium/issues/detail?id=1367190

**Comment by flackr** [comment]
We discussed this today and came to the following rough plan of action:
1. Fire mousedown (and other compat mouse events) to the still attached ancestor. This ensures that ancestor listeners still see the events that they would expect to see.
2. Use the common ancestor of the pointerdown and pointerup events to target the click event - this will make it so that the above change does not result in click being fired on element removal during the pointerdown.
3. Remember the element targeted by the pointerdown even if it is removed from the DOM. This supports re-ordering DOM cases like [crbug.com/1367190](https://bugs.chromium.org/p/chromium/issues/detail?id=1367190) as we remember the original target before the reordering happened. The behavior is consistent with if you changed the position on down but the user moved their mouse to again be over the same element.
