### ISSUE TITLE
Clarify whether `pointermove` will be dispatched if `pointerrawupdate` listener removes the document

### ISSUE THREAD

**Issue by masayuki-nakano** [w3c/pointerevents#510]
If a `pointerrawupdate` event listener in a subdocument removes the `<iframe>` itself from the parent document or moves the `<iframe>` to different place and the element under the `pointerrawupdate` is changed, should browsers dispatch `pointermove` on the parent document (or another subdocument if another `<iframe>` is moved at the pointer)?

It could lead complicated issues and makes the dispatcher in the browsers more complicated if browsers lock the target of `pointerrawupdate` for `pointermove`. So, perhaps, `pointermove` should not be fired on the unloaded document nor the different document.

**Comment by smaug----** [comment]
"The target of [pointerrawupdate](https://w3c.github.io/pointerevents/#dfn-pointerrawupdate) events might be different from the [pointermove](https://w3c.github.io/pointerevents/#dfn-pointermove) events due to the fact that [pointermove](https://w3c.github.io/pointerevents/#dfn-pointermove) events might get delayed or coalesced, and the final position of the event which is used for finding the target could be different from its coalesced events." so I'd expect pointerrawupdate be quite separate event from pointermove, target explicitly can be different. In same origin case that should be quite doable (and cross-origin iframe case the pointermove event might get lost)

**Comment by smaug----** [comment]
In other words, I think the spec is fine. It is clear enough that pointermove is a separate event. Some new tests are of course always welcome.

Could we close this?

**Comment by masayuki-nakano** [comment]
Yeah, I think so. I'm not sure whether this can be testable with WPT because of the document boundary.
