### ISSUE TITLE
Pointer Id across different iframes

### ISSUE THREAD

**Issue by NavidZ** [w3c/pointerevents#52]
There is no indication of whether the user agent is allowed to use different ids for the same pointer across multiple iframe or not.
It seems that what Edge uses as pointer id somewhat comes from the OS it is kind of unique.

I was wondering if that was the intention and if so is it worth to add a note to make sure the id of the same pointer is preserved across different iframes?

**Comment by patrickhlauke** [comment]
i don't believe - at least from my reading/understanding of the spec - that the intention is for `id` to be consistent across documents/iframes. are there scenarios where it would make a developer's life difficult if the `id` isn't kept the same (something like dragging from a parent to a child iframe, for instance...though i don't think that's easily achievable anyway at this stage)?

**Comment by NavidZ** [comment]
I vaguely recall that @RByers was saying that if the iframes talk with each other say with postmessage api about one pointer event they should have a way to talk about the same pointer event. If the ids are different then that use case seems impossible.

**Comment by RByers** [comment]
Yeah I think there could be scenarios.  I've seen some crazy examples of co-ordination between script running in iframes and their parent frame and doing some co-ordination around input (Eg. capture handoff) is not impossible.  If the ID is consistent across frames in Edge, then I'd say we should just put that into the spec - it's a better design IMHO.

**Comment by patrickhlauke** [comment]
> f the ID is consistent across frames in Edge, then I'd say we should just put that into the spec - it's a better design IMHO

frames/iframes, or are we going further and recommend/suggest it's consistent across documents (e.g. two separate browser windows, side by side. are there further implications, such as a pointer leaving the document and then returning, and making sure that the same `id` is maintained in those scenarios as well, etc?

**Comment by RByers** [comment]
That's a good question, though less likely to matter in practice.  @NavidZ I forget, we do ID remapping inside of blink, right?  If so providing this same-ID property across different tabs would be broken, and even across different frames in the OOPIF case.

**Comment by NavidZ** [comment]
Yes. That is right. As of now we do it in Blink but I believe we can always move it up in the stack to have it more broader. However, the question is that whether we would like to support such a feature or not.
If we decide not to it might be better to also not have the consistent ids across any iframes to make sure developers don't make any assumptions based on a few samples they may see. What do you think?

**Comment by RByers** [comment]
I think the least surprising thing for developers is if the IDs are completely consistent (they will think of them as a property of the actual input, not the particular browsing context).  If this is already how Edge behaves and it's not much work to make blink match, then I suggest we just put that into the spec.  As always, minimizing the risk of developer confusion is more important that simplifying UA implementation.

**Comment by RByers** [comment]
Discussed [on the call](https://www.w3.org/2016/04/26-pointerevents-minutes.html#item04) today.

We agreed that the IDs should at least be consistent for a given top-level browsing context (tab) as this could be valuable in some scenarios.  @NavidZ is going to prepare a spec PR for this.

It's an open question whether it's worth trying to define consistency on a broader scope.  Eg. it's possible that some drag-between-windows scenario could communicate between pages (even via a server) to handle the input properly.  But it's not clear this is even possible today due to OS-level window input capturing.  @teddink said he'd investigate the behavior on Windows further (they do support cross-window HTML5 drag-and-drop events).  Also because Chrome and Firefox can't rely on the OS to provide unique IDs in the correct form (eg. on Linux) it may not be possible to implement a truly global ID mapping on all OSes (Edge gets this for free from Windows).

**Comment by RByers** [comment]
Filed #59 for the harder (but less important) question of what to do across different top-level browsing contexts.
