### ISSUE TITLE
How removing target in pointer event handler affects compat mouse event target

### ISSUE THREAD

**Issue by NavidZ** [w3c/pointerevents#64]
There is this paragraph in the spec:

Unless otherwise noted, the target of any mapped mouse event should be the same target as the respective pointer event unless the target is no longer participating in its ownerDocument's tree. In this case, the mouse event should be fired at the **original target's nearest ancestor node (at the time it was removed from the tree) that still participates in its ownerDocument's tree**, meaning that a new event path (based on the new target node) is built for the mouse event.

However the new target seems not to be correctly worded based on what Edge does and makes sense at least to me. Maybe the new target should be the "nearest ancestor node in the propagation path of the corresponding pointer event" instead.

The difference is that if the pointer event handler reparents the target and then removes it from the document, the existing wording seems to imply that the mouse event target should be the new parent. But the new wording says it should be sent to the original parent.

Here is an example:
https://output.jsbin.com/mobeju

**Comment by scottgonzalez** [comment]
Since that's not the easiest thing to follow with all the output, I'll paste the output for the sanity of everyone else that looks at this issue (please do this in the future):

```
green pointerdown green
grey pointerdown green
grey mousedown grey
grey mousemove grey
grey pointerup grey
grey mouseup grey
```

> The difference is that if the pointer event handler reparents the target and then removes it from the document, the existing wording seems to imply that the mouse event target should be the new parent. 

I assume that by "reparents the target" you mean if the node is appended to a different element. Moving the node requires two steps: removing the node, then inserting the node. The spec already makes it clear that the path traversal is based on the DOM at the time of removal.

I see nothing that indicates the event should start propagating through the new parent.

**Comment by NavidZ** [comment]
Sure.
My confusion was that from the js point of view you can just call one single API like appendChild and move a node from a its current parent to another one. I was reading a bit further and looking at the appendChild documentation it does mention that it gets removed first and gets added to the new node as you mentioned.
