### ISSUE TITLE
Default width/height attribute for mouse

### ISSUE THREAD

**Issue by NavidZ** [w3c/pointerevents#65]
Spec is sort of silence about the default value of width and height property of devices that are not reporting the actual geometry of the pointer particularly mouse.

"The width (magnitude on the X axis), in CSS pixels (see [CSS21]), of the contact geometry of the pointer. This value may be updated on each event for a given pointer. For devices which have a contact geometry but the actual geometry is not reported by the hardware, a default value should be provided by the user agent to approximate the geometry typical of that pointer type. Otherwise, the value must be 0."

Edge reports width=height=1 for mouse or the normal pen. In our current Chrome implementation we  report 0. I wanted to match the behavior of Edge but I thought If we are matching the behavior in this level is it worth it to maybe add a note of some sort to also mention this in the spec or not. WDYT?

**Comment by scottgonzalez** [comment]
I would expect the value to be 1 for mice.

**Comment by teddink** [comment]
Adding a note is fine - like Scott I would expect the value to be one for mice and pen and trackpad, unless of course the HW device reports something more specific and granular.

**Comment by patrickhlauke** [comment]
Not sure where we'd put the note though. As part of the definition of `width`, of `height`, of both, or - very disconnected - after all the interface definitions?

Personally, I think authors would simply expect a value of 1 for `width` and `height` in the case of a mouse and stylus...not sure it needs spelling out explicitly.

**Comment by mustaqahmed** [comment]
I agree that adding a note could be a bit tricky here. But what about changing the default value to 1 (from 0)?

A device which doesn't know about the contact geometry still must report a pointer coordinate that essentially "points" to a CSS pixel---I guess this is why we easily agreed that mouse/pen/trackpad should have default 1.

**Comment by patrickhlauke** [comment]
I guess the difference here is: if I query the property and get 0, this clearly means that the hardware/OS/UA had no idea what the width/height were and did not even attempt to make a guess (which, depending on what pointer type this came from, can tell the author that they need to do their own guessing/choosing a value for whatever their code does). If we standardise to 1, it may be a device that truly has a 1x1 px "tip" or it may be the former case.

**Comment by NavidZ** [comment]
So with this discussion should we maybe set the width and height of mouse pointers to 0 as well and let the author decide what to do with that?

**Comment by patrickhlauke** [comment]
i would say no. for mouse the browser DOES know (or rather, it can strongly infer it) that it's 1x1 pixels, and is free to report it having `width` and `height` of 1 if it so desires. my concern, however, is that if we define the default/fallback in general (for all pointer types) as 1, then in situations where i as an author receive a touch pointer with reported 1x1, how can i be sure if it's just the browser falling back to default because the hardware/OS didn't actually report the true touch geometry, or if it's a super-fine-control touchpoint (like one of those "dumb" styluses which simply act as a capacitive surface/really thin finger) (or, i guess, a VERY low-dpi touchscreen, like a giant wall-sized touchscreen or something)?

As an aside, note how on the Nokia Lumia 520 / Windows 10 Mobile / Edge, `width`/`height` are reported as 0 for touch (as the hardware does not capture geometry, and the browser didn't want to guess/fake a value) http://patrickhlauke.github.io/getting-touchy-presentation/#338

**Comment by mustaqahmed** [comment]
Just realized that the current wording for the default value ("_Otherwise_, the value must be 0") also covers the case when the geometry is _undefined_, e.g. for a hovering stylus. This is another strong argument to rule out my suggestion to change the default value :-(

I think we need a note to highlight the hovering stylus case (in addition to fixing the main issue here) since it is easy to miss this tricky corner case. (This is only remotely related to #14.)

**Comment by patrickhlauke** [comment]
> also covers the case when the geometry is undefined, e.g. for a hovering stylus.

is there a need to differentiate between "the hardware doesn't capture geometry info, and the browser didn't want to fake it, so the value is 0" and "the hardware DOES capture geometry, and it's really a hovering pointer (i'm including hovering touches here as well, a la https://blogs.msdn.microsoft.com/msr_er/2016/04/28/enhanced-virtual-reality-among-new-microsoft-research-advances-at-chi-2016/)" ? if so, perhaps we do want to have an actual `undefined` value too, or `-1`, for the former case?

**Comment by teddink** [comment]
That is indeed an interesting use case - in the end Edge relies on the HW and the OS Platform to report that information to us. In the case of Windows Phone the OS tells us that width and height are 0 for touch input, so that is what we plumb through. Similarly, at least on my touchscreen enabled desktop, we get and report 26 for the width and height for touch input. I am not sure what the OS reports for a hovering pen - hmmm, trying now.

**Comment by dmethvin** [comment]
It seems like 26 is a somewhat bogus answer that isn't dependent on the actual width of pointer contact. I get 26 on my Lenovo X1 Carbon in Edge and 21 in IE11, regardless of the fatness of the finger I use. :smile: Also, if the screen is zoomed by a double-tap the value becomes a constant 14 on both browsers. :question: 

http://jsbin.com/fefise/edit?html,js,console,output

If this value is going to have future utility, the OS or browser should not fill in numbers if it really doesn't know. Let a width/height of 0 or undefined represent a missing or unsupported value. Software at the application level can recognize that and provide a default. (How would hovering touch devices be handled anyway? Seems like you'd want some sort of opt-in at `addEventListener` time and an elevation value on events?)

For mouse cursors, on Windows at least a cursor editor makes you define a hot spot (generally the top left) and the rest of the cursor takes up space on the screen but is not part of the hot spot. So it would seem for that case you could validly define the width/height of the pointer to be 1x1?

**Comment by teddink** [comment]
Updated info - here is what we are seeing in practice:

**Surface Book**
Pen Hover = 1, 1
Pen in Contact = 1, 1
Touch = ~50, ~50 (varies based on the size and shape of your finger)

**Surface Pro 4**
Pen Hover = 1, 1
Pen in Contact = 1, 1
Touch = ~50, ~50 (varies based on the size and shape of your finger)

**Comment by patrickhlauke** [comment]
> How would hovering touch devices be handled anyway? Seems like you'd want some sort of opt-in at `addEventListener` time and an `elevation` value on events?

I would expect these to be, in the first instance, similar to hovering stylus/pen pointer events `pointerType == "touch"`,  `pressure == 0`, `width == 0` and `height == 0`. and then yes, a new property `elevation` on the pointer event object

**Comment by patrickhlauke** [comment]
> If this value is going to have future utility, the OS or browser should not fill in numbers if it really doesn't know. Let a width/height of 0 or undefined represent a missing or unsupported value. Software at the application level can recognize that and provide a default.

So removing this, basically?

> a default value should be provided by the user agent to approximate the geometry typical of that pointer type

Incidentally, for Touch Events, I seem to recall that some browsers do the same "fake" estimation of `radiusX`/`radiusY` (and on some devices, use these values to fake `force` even on non-pressure-sensitive touchscreens). however, http://w3c.github.io/touch-events/#widl-Touch-radiusX seems more specific that UAs should simply report 0 here and not approximate anything.

I could live with that - but if we do this, it should be done very soon before there's a critical mass of sites/apps that rely on the "faked" geometry values

**Comment by RByers** [comment]
I agree that Mouse/Pen have a definite size (1,1) (although you could argue that on some HighDPI systems it might be (0.5,0.5) etc.).  I also agree that we want to differentiate that definite size from unknown.  Navid, did you see this difference affecting some size behavior in practice?

For TouchEvents we've worked to only expose `radius` values when we're supplied with values we trust from the OS.  Eg. on Windows I believe we always report `0` because the values we get via WM_TOUCH in practice seem entirely unreliable.

**Comment by patrickhlauke** [comment]
> For mouse cursors, on Windows at least a cursor editor makes you define a hot spot (generally the top left) and the rest of the cursor takes up space on the screen but is not part of the hot spot. So it would seem for that case you could validly define the width/height of the pointer to be 1x1?

are there any potential scenarios (current or future) where a system may have a different `width`/`height` somehow for mice? some kind of "fat mouse" setting (which allows users more coarse pointing, and uses same sort of averaging/smoothing/heuristics [ed: as touch] to determine what they actually did want to activate when they click the mouse button)? it's...conceivable? if so, i'd rather not write in assumptions (see also my recent edit opening up the possibility of multiple simultaneous mice)

**Comment by patrickhlauke** [comment]
> Eg. on Windows I believe we always report 0 because the values we get via WM_TOUCH in practice seem entirely unreliable.

On my Surface 3 (which does detect touch geometry), using http://patrickhlauke.github.io/touch/tracker/multi-touch-tracker-pointer-hud.html Chrome seems to consistently fake a `radiusX` and `radiusY` of 25

**Comment by patrickhlauke** [comment]
> some kind of "fat mouse" setting

having said that, I guess in those scenarios the OS itself would handle the heuristics of determining what the user _actually_ wanted to activate/hover over/etc, and would then simply send 1x1 "points" on to the application layer...

**Comment by patrickhlauke** [comment]
so next question: can we conceive of a situation where a stylus/pen might have variable geometry? like having a fat rubber/erase type end where you could just touch on an edge and have a very small contact, or use the flatter part for a larger contact?

otherwise, we could probably define that:
- if it's an input device type that can have variable geometry (touch), the value of `width` and `height` must reflect the geometry as reported by the hardware. if the hardware does not support this, the value must be 0
- for input devices that don't have variable geometry (typically mouse and stylus), the value of `width` and `height` must always be 1

**Comment by dmethvin** [comment]
> So removing this, basically?
> 
> > a default value should be provided by the user agent to approximate the geometry typical of that pointer type

:+1:

> some kind of "fat mouse" setting

I guess the spec doesn't have to preclude the existence of a "fat mouse" but a typical mouse could still be 1x1. 

> otherwise, we could probably define that: 
> - if it's an input device type that can have variable geometry (touch), the value of width and height must reflect the geometry as reported by the hardware. if the hardware does not support this, the value must be 0
> - for input devices that don't have variable geometry (typically mouse and stylus), the value of width and height must always be 1

If not 1 then some fixed value representing its hotspot if you still want fat mice.

**Comment by NavidZ** [comment]
There were 2 points that were mentioned regarding possibility of a mouse not having a width=height=1. One is some kind of a "fat mouse" and the other one is in the high DPI systems that the point is event smaller than 1,1. So the question I'm having here is that why would ask the browser to do any guessing at all for the width and height of a device that doesn't report any? Basically if an app really cares about such a thing they should know that they device is not reporting that information and they make their own guesses instead of us making a guess for them and that guess might not be good for them in the context of their app. However, I understand that Edge is shipped with that width=height=1 in this case and I'm not sure if it is possible to change that.
Note that here if we set height=width=1 for a typical mouse or even a pen that doesn't report such information we are making it the same as a mouse or pen that can report width and height and they are reporting 1.

**Comment by RByers** [comment]
I think I remember talking with @jacobrossi about this back in the day and the argument for 1 was that it makes it easier to write code that wants to just use width/height without having to provide a default case.  I can also see the argument for being able to differentiate the unsupported case.  But this is all pretty niche, not worth a lot of effort or compat risk IMHO.

I'd suggest we should just spec 1x1 as the default and if a scenario arises where it's useful to know whether a device truly supports reporting geometry then we can just add a bool for that to the `InputDeviceCapabilities` API.

**Comment by patrickhlauke** [comment]
i was going to initially argue back with some concepts of purity etc...but you know what, I can actually live with making `width` and `height` default to `1` under some form of philosophical understanding that by this we mean that a "pointer" always needs to point somewhere, so has to have at least 1x1 CSS pixel size.

happy to draft up a PR for this later today...

**Comment by patrickhlauke** [comment]
PR #69 for review, which i believe captures the overall feeling here of making `1` the new default value (with explicit mention of mouse/stylus), and removing the UA guessing/faking game...

**Comment by patrickhlauke** [comment]
while i'm in that area, a nitpick

```
This value MAY be updated on each event for a given pointer
```

isn't this the wrong way around? isn't it that if the geometry changes, it will fire an event? or am i splitting hairs?

**Comment by patrickhlauke** [comment]
answering my own question - yes, i'm probably splitting semantic hairs here, i think the meaning here is clear enough for now

**Comment by RByers** [comment]
I agree, if the geometry is updated the UA MUST fire a `pointermove` to indicate that.
