### ISSUE TITLE
Add feature detection section

### ISSUE THREAD

**Issue by RByers** [w3c/pointerevents#94]
Discussed on the call today that we should add a non-normative section about suggested feature detection.  Perhaps something like this?

``` javascript
  if (window.PointerEvent) {
    // Listen only for pointer events when they're supported.
    // Don't bother listening for mouse/touch as they're redundant and will only cause confusion.
    target.addEventListener("pointerdown", ondown);
    ...
  } else {
    // Listen for both touch and (non-touch-derived) mouse events.  No need for feature detection.
    target.addEventListener("touchstart", ondown);
    target.addEventListener("mousedown", function(e) {
      if (!e.sourceCapabilities || !e.sourceCapabilities.firesTouchEvents)
        ondown(e);
      });
    ...
  }
```

@patrickhlauke says he'll write up a PR to discuss further.

**Comment by NekR** [comment]
If v2 will be different than v1 (incompatibilities), how can one detect the new version without UA checks?

**Comment by patrickhlauke** [comment]
As v1 is only really implemented in IE11 and early versions of Edge, and v2 is effectively a realignment of what Edge does now and what Chrome and Mozilla are targetting, I don't think this will be a huge problem.

**Comment by patrickhlauke** [comment]
(sorry, accidentally closed this issue by accident)

**Comment by NekR** [comment]
Okay, just to clear some things.
Imagine my website has support of both mouse and touch events. Now I wan't to add Pointer Events (v2) support because it's better, simpler, etc. So I am doing this:

``` js
if (window.PointerEvent) {
  initNewInputSystem();
} else {
  initOldInputSystem();
}
```

Question is: will my Pointer Events v2 implementation be _fully_ compatible with old Pointer Events v1 (IE11/earl Edge) without any hacks/changes?

**Comment by patrickhlauke** [comment]
As Edge is evergreen, it likely then comes down to: will my code work in IE11. In which case: if the code does rely on anything substantively different as per https://w3c.github.io/pointerevents/#revision-history then you will likely have issues (unless it's one of the changes to the spec that are more clarifications of things that even IE11 already did differently from the nominal Level 1 spec). @teddink may be able to clarify if the behavior of PE in IE11 may still receive updates or not. @rbyers may have further thoughts on whether some method to explicitly distinguish between Level 1 and Level 2 support is required or not.

**Comment by RByers** [comment]
Since we don't yet know exactly what breaking changes Level 2 will have, I think it's premature to try to account for this here.  Any breaking changes will be around edge cases, so we almost certainly wouldn't want any sort of master versioned feature detect (not "if (PE Level 2) else if (PE Level 1) ...)".

Instead I think we should discuss feature detection of _specific_ breaking changes along with any spec work for those breaking changes (i.e. a great discussion for #8).

**Comment by teddink** [comment]
I agree with Rick - we have not made any breaking changes yet and it would be easier to discuss them specifically rather than in the abstract. In general, we would certainly seek to avoid them whenever we can.

Microsoft Edge is indeed evergreen and will be the platform and browser application that will receive all functional updates as time marches on. It would be best to think of IE11 as in maintenance mode - it will only receive security updates. IE11 is meant to be a compatibility browser - especially for Enterprise customers who still rely on older web and browser technologies.
