### ISSUE TITLE
What should be the 'detail' property of pointer events?

### ISSUE THREAD

**Issue by NavidZ** [w3c/pointerevents#98]
From the UI Event spec, mouse events should have 'detail' property set to the click count. Do we expect the same for the pointer events?
Currently both Edge and Chrome set this property to 0 all the time.
I believe either way we need a note to define the value of this property somewhere.

**Comment by patrickhlauke** [comment]
noob question: what does this `detail` property even mean? click count? (as in what's meant by "click count"?)

(i'm guessing as PE extends mouse events, it doesn't necessarily need to define everything, since it doesn't define all the various `clientX`, `clientY`, `pageX`, `pageY` etc attributes that come from mouse event either)

**Comment by NavidZ** [comment]
That is correct. It is click count. Alternatively we can say 'detail' is always zero and we can add another property 'clickcount' to pointerevents to make it more clear.

The way it is defined in UI Event is that the particular events like "mousedown", "mouseup", ... and stuff like that have this definition of detail. So although pointerevent is the child of mouseevent structure we still might need a note mentioning that we do the same for "pointerdown", "pointerup", ...
However, one more important question maybe for @jacobrossi or @teddink is whether there was a reason they set this property to 0 in Edge?

**Comment by RByers** [comment]
There's two different types of compat competing here:
1. Compat with Edge's existing behavior: it's possible, thought unlikely, that by setting `detail` to non-zero it could break some websites.
2. Compat between `PointerEvent` and `MouseEvent`: it's possible that having detail=0 is breaking some code originally designed for `MouseEvent`.  Since Edge has presumably always had this behavior, I'm assuming the risk here is very low.

FWIW I consider the use of `detail` for this in UIEvents to be a hack for legacy reasons (very few people understand it, having a property whose semantics vary depending on the event is ugly).  Given that Edge has just been using 0, my preference would be to match that behavior.  If knowing the click count is actually valuable to anyone (I think it probably is), we should just define a new `clickCount` property to represent it explicitly.

**Comment by patrickhlauke** [comment]
Does Edge actually set anything sensible for `details` in the case of real mouse events? Reading the UI spec, it does smell of a fairly hacky attribute, and I agree that it's doubtful any new code targetting PE would also rely on this attribute (but I might be wrong), so I'd simply quietly ignore it/not mention it.

**Comment by RByers** [comment]
Yes, Edge appears to match Chrome in this regard.  Eg. on a double tap you get mousedown/mouseup with `detail=1` and then with `detail=2`.

**Comment by teddink** [comment]
Based on what history we have available to us, we just considered event.detail to be a legacy property, so we matched chrome’s interop of support for mousedown, mouseup, click, dblclick events but didn’t extend further. 

We are open to doing the same for pointerup/pointerdown if we think that there is any value to it (which we doubt). We are also open to adding a clickcount property, pending some deeper investigation into implementation approach.

**Comment by RByers** [comment]
Thanks Ted.  Yeah let's not perpetuate the confusing use of `detail` any further.  I do think there are legitimate uses for looking at the click count on `click` today (eg. I worked with one developer trying to detect double-tap - I really didn't want them relying on their own timer).

So let's plan on specifying a new `clickCount` property to replace `detail`, but this can safely be low priority (eg. maybe not level 2).

**Comment by patrickhlauke** [comment]
So should we say anything directly in PE Lvl2 about `detail` ? Or just quietly leave it unmentioned?

**Comment by RByers** [comment]
I think we should explicitly say it should have the value 0 (otherwise it's reasonable to think there's a bug in the existing implementations).

**Comment by RByers** [comment]
Let's leave this open until the tests have also been updated.

**Comment by NavidZ** [comment]
Yup. I'm working on the test in this issue.
https://github.com/w3c/web-platform-tests/issues/3349

**Comment by RByers** [comment]
Ah, thanks.  IMHO it's not worth opening separate issues in web-platform-test, we should just get in the habit of having a single issue here for spec+test changes.

**Comment by NavidZ** [comment]
Sure. I'll do that for the future tests.

**Comment by NavidZ** [comment]
I believe I updated the test for this issue. I'll close it then.

**Comment by my2iu** [comment]
Was the `clickCount` idea added to the spec in the end? I'm encountering problems with using pointer events because I can't detect double-clicks without using mouse events, but having mouse events and pointer events coexisting causes problems too because some browsers send certain touch events twice--once as pointer events and again as mouse events--and all sorts of headaches like that.

**Comment by patrickhlauke** [comment]
no, a new `clickCount` was deemed too low priority for PE Level 2. it may be revisited in future version of the spec though.

**Comment by NavidZ** [comment]
Btw, if you care about the click action you should really listen to the click or auxclick events as well (and just check the detail field for click count). Sometimes UA suppress click event if they believe the user didn't mean to activate anything. We were thinking of adding pointer properties like type and whatnot to click event which is also under debate.

**Comment by stefnotch** [comment]
Is there an issue that I can follow regarding the `clickCount`? I know of one library that has to do some dirty hacking to use the `detail` property from mouse events to reliable detect double clicks.
https://github.com/arnog/mathlive/blob/794c8778f4d7f94b51b0cf7c80fe4a325b679604/src/editor-mathfield/pointer-input.ts#L188

**Comment by mustaqahmed** [comment]
The `event.detail` field is currently well-defined in the specs: it gives the click-count for [`click`](https://w3c.github.io/uievents/#event-type-click) and [`auxclick`](https://w3c.github.io/uievents/#event-type-auxclick).  For all other PointerEvent types, the field is [zero](https://w3c.github.io/pointerevents/#attributes-and-default-actions).

I am not sure why the mathlive code linked above is relying on `event.detail` of a `pointermove` or `mousemove`.  I don't know any browser that reports click-counts on these events.

**Comment by stefnotch** [comment]
That's a good point. I suppose Mathlive's code usually ends up using the manual option for detecting double clicks.
Which means it's using Date.now() to detect double clicks
https://github.com/arnog/mathlive/blob/794c8778f4d7f94b51b0cf7c80fe4a325b679604/src/editor-mathfield/pointer-input.ts#L116-L132

Based on this comment, I'm assuming using a timer is the one option that should be discouraged.
> (eg. I worked with one developer trying to detect double-tap - I really didn't want them relying on their own timer).
> -- @[RByers](https://github.com/RByers)

Hence my question about the future `clickCount` property for pointer events.


P.S. Firefox seems to actually set the `event.detail` property for mousemove events.
```js
window.addEventListener("mousemove", (evt) => {
console.log(evt.detail)})
```
![image](https://github.com/w3c/pointerevents/assets/10220080/0aa9f640-a9ec-43b8-89a0-205b9ef2f5ee)

**Comment by patrickhlauke** [comment]
the point seems to be that `details` is an old, legacy, and unreliable property. so despite comments from 2016 on this thread, it doesn't look like there will be any movement on this I'm afraid.

**Comment by stefnotch** [comment]
That'd be a shame. Does that mean there's no good and cross-platform way of detecting a doubleclick?

The options are
1. Use a timer, and ignore the native settings. That seems like a really bad option
![windows settings for double clicking](https://www.elevenforum.com/attachments/mouse_doubleclickspeed-png.27797/)
2. Use an old and unreliable property. And listen for mouse events instead of pointer events, just to get the details property.

**Comment by mustaqahmed** [comment]
> Does that mean there's no good and cross-platform way of detecting a doubleclick?

If a site uses a non-standard behavior instead of a `dblclick` event, it is not a spec problem.  Both specs are good here as @patrickhlauke mentioned.

> Firefox seems to actually set the event.detail property for mousemove events.

In my own [testing](https://rbyers.github.io/eventTest.html), Firefox and Chrome always shows `0` from a `mousemove` as per the spec.  I tried both Linux and Windows.  I also tried your event-listener code, got `0` all the time.  If you are seeing a non-standard behavior, file a bug to Firefox.  Again, this repository is for spec discussion only.

**Comment by stefnotch** [comment]
Using the dblclick event would not work, since Mathlive is doing "double click to select text".

The dblclick event fires after "down up down up" events. At that point the mouse button has been released.

However, a text selection double click has to fire sooner. It has to get detected after "down up down", if that makes sense.

Hence, a good solution involves using the detail property of a mouse*down* event. Is that the appropriate and officially blessed solution, or would further spec work be appropriate?

**Comment by enexusde** [comment]
I have an Issue that one single mouse-click creates two PointerEvents. 
The first PointerEvent have a details of 1
The second PointerEvent have a detail of 0

I could reproduce it in Chromium (Version 123.0.6312.86 (Offizieller Build) snap (64-Bit)) and Firefox (124.0 (64-Bit)) on Ubuntu!

HTML Code: 
```
<body>
	<div id="wrap">
		<div class="calendar">
			<label class="today_is_f daygap0 unknown" 
                                          onclick="console.log('event.detail:',event.detail);">
				<input type="radio" name="cal750" checked="">
				<span>5</span>
			</label>
		</div>
	</div>
</body>
```


Output of the click onto the optionbox:  
```
event.detail: 1
event.detail: 0
```
If I doubleclick onto the optionbox this is the output:
```
event.detail: 1
event.detail: 0
event.detail: 2
event.detail: 0
```
As you might have noticed, I use the html-attribute "onclick".
